### ISSUE TITLE
Typo in SP reset credentials

### ISSUE THREAD

**Issue by ddavtian** [spinnaker/spinnaker.github.io#1007]
Page: [/setup/install/providers/azure/](https://www.spinnaker.io/setup/install/providers/azure/)

Feedback: The correct syntax to reset the sp password is: `az ad sp reset-credentials --name <app_id>`

**Comment by dorbin** [comment]
@ddavtian I see `az ad sp credential reset` on [this page](https://docs.microsoft.com/en-us/cli/azure/ad/sp/credential?view=azure-cli-latest#az-ad-sp-credential-reset), but do not see `az ad sp reset-credentials`.

If there's a `reset-credentials` version, could you point me to the doc?

Thanks!

**Comment by dorbin** [comment]
@ddavtian 
Closing this for now, but feel free to reopen if I'm in error.
Thanks!
