### ISSUE TITLE
Automating Canary Analysis on Google Kubernetes Engine with Spinnaker 

### ISSUE THREAD

**Issue by shreesri** [spinnaker/spinnaker.github.io#1090]
Hi Team,

As per the following documentation "https://cloud.google.com/solutions/automated-canary-analysis-kubernetes-engine-spinnaker#whats-next". we created the canary deployment pipeline with manually judgement. with using the following command 

`wget https://raw.githubusercontent.com/spinnaker/spinnaker/master/solutions/kayenta/pipelines/canary-deploy.json
export PIPELINE_ID=$(curl \
    localhost:8080/gate/applications/sampleapp/pipelineConfigs/Simple%20deploy \
    | jq -r '.id')
jq '(.stages[] | select(.refId == "9") | .pipeline) |= env.PIPELINE_ID | (.stages[] | select(.refId == "8") | .pipeline) |= env.PIPELINE_ID' canary-deploy.json | \
    curl -d@- -X POST \
    -H "Content-Type: application/json" -H "Accept: /" \
    http://localhost:8080/gate/pipelines
 `
we manually imported the json using UI mode. But we are getting following error at Find Baseline Version stage . please find the below error screenshot.  Please help us to resolve the same.

![image](https://user-images.githubusercontent.com/30147002/48054260-dce24c00-e1d2-11e8-9169-cfdd7378d10a.png)

We used following json file for FindBaselineVersion.
```{
  "application": "sampleapp",
  "comments": "",
  "executionOptions": {
    "successful": true
  },
  "expectedArtifact": {
    "id": "e00b39b2-e6a1-41a7-8e1a-bef37c3313a7",
    "matchArtifact": {
      "kind": "custom",
      "name": "sampleapp-config-prod",
      "type": "kubernetes/configMap"
    }
  },
  "name": "Find Baseline Version",
  "pipeline": "3ed897e9-5c44-47e0-b93e-ae5eba3f475b",
  "type": "findArtifactFromExecution"
}```
=======================
Please find the below configmaps output.

kubectl get configmaps

NAME                           DATA      AGE
sampleapp-config-canary-v000   1         20h
sampleapp-config-canary-v004   1         19h
sampleapp-config-canary-v005   1         19h
sampleapp-config-prod-v000     1         5d
sampleapp-config-prod-v001     1         19h
sampleapp-config-prod-v004     1         18h

**Comment by dorbin** [comment]
@MrTrustor

**Comment by MrTrustor** [comment]
@shreesri can you post the following information?

- The full JSON spec for the _Simple deploy_ pipeline given directly by the Spinnaker API? If you have port-forwarding setup like in the tutorial, you should be able to get it by executing: `curl http://localhost:8080/gate/applications/sampleapp/pipelineConfigs/Simple%20deploy`
- The full JSON spec for the _Canary Deploy_ pipeline with `curl http://localhost:8080/gate/applications/sampleapp/pipelineConfigs/Canary%20Deploy`
- The full JSON description of the **last** execution of the _Simple deploy_ pipeline that you can get by clicking on the small "Source" link at the bottom of the details of that execution (see screenshot).

<img width="1070" alt="screen shot 2018-11-06 at 23 42 22" src="https://user-images.githubusercontent.com/2864678/48101127-e5ac3f80-e21d-11e8-81e2-b4a98b90407e.png">

- The full JSON description of a failed execution of the _Canary Deploy_ pipeline where you have the problem. (By using the same source link).

Please do not post the full json files here, but on a gist, pastebin or another similar service.

When you say "we manually imported the json using UI mode", what json file are you talking about? The tutorial never asks you to import a JSON file by copying and pasting it in the Spinnaker UI. I suspect that this is the source of the problem.

**Comment by shreesri** [comment]
issue resolved
