### ISSUE TITLE
Monitoring documentation needs to be updated

### ISSUE THREAD

**Issue by ttomsu** [spinnaker/spinnaker.github.io#1094]
Page: [/reference/monitoring/](https://www.spinnaker.io/reference/monitoring/)

Feedback:

> Monitoring is enabled in the microservices using the Halyard command TBD.

I believe these commands exist and the docs need to reflect this.

**Comment by dorbin** [comment]
@ewiseblatt 
@lwander 

There's no `hal config monitoring enable`. Is the correct command instead `hal config metric-stores <telemetry provider> enable`? Or do we still not have the general enable monitoring command yet?

**Comment by ewiseblatt** [comment]
https://github.com/spinnaker/spinnaker.github.io/pull/1095

**Comment by ewiseblatt** [comment]
Looking at halyard, I see that it is enabling monitoring if you enabled a provider. That actually is not the intended behavior. You shouldnt need a provider to enable monitoring so that you can scrape the services to add your own provider outside halyard.

**Comment by ewiseblatt** [comment]
In the code base itself, monitoring is off by default, but you can turn it on with a service config spectator.webEndpoint.enabled: true.

Halyard [currently] writes this value depending on whether or not you have a specific store enabled.

**Comment by dorbin** [comment]
The current doc, /reference/monitoring/ says monitoring is *enabled* by default. That's the paragraph which you've deleted in the PR you referenced above. Was that an erroneous statement?

**Comment by ewiseblatt** [comment]
It was, but that wasnt why I deleted it. I did not realize it was wrong
until just after. I deleted that section because just above I stated that
document was not about config or setup and referenced the other document.

I checked the other document and it does not make claims about the default
value. It shows how to setup the different providers which would enable it
so seemed consistent.

**Comment by dorbin** [comment]
This is resolved in #1095.

Thank Eric!
