### ISSUE TITLE
Cannot edit front50-local.yml

### ISSUE THREAD

**Issue by wfhartford** [spinnaker/spinnaker.github.io#1123]
Page: [/setup/install/storage/minio/](https://www.spinnaker.io/setup/install/storage/minio/)

Feedback:

The directions for configuring minio ask me to add a line to a file at `~/.hal/$DEPLOYMENT/profiles/front50-local.yml`; this file does not exist.

I think I've followed the instructions pretty faithfully, but the `~/hal/default/profiles` directory does not exist. I've run halyard in kubernetes, attempting to install to that kubernetes cluster. All of the steps in the instructions have run as expected.

**Comment by wfhartford** [comment]
I think I understand now that the directory and file would most likely have to be created at that point. Could a note be added to that part of the documentation indicating that the file should be created if it does not exist?

**Comment by duftler** [comment]
Sure: https://github.com/spinnaker/spinnaker.github.io/pull/1125
