### ISSUE TITLE
executing the pipeline with parameters.

### ISSUE THREAD

**Issue by kychoolkim** [spinnaker/spinnaker.github.io#1185]
Page: [/guides/spin/pipeline/](https://www.spinnaker.io/guides/spin/pipeline/)

Feedback:
It would be nice if it has the usage for parameter file and its example.

**Comment by jtk54** [comment]
There is a [blurb below the command](https://www.spinnaker.io/guides/spin/pipeline/#create-and-update-pipelines-with-save) that describes the usage and format of the file that you supply to the `--file` flag. What is missing?

**Comment by jtk54** [comment]
I misunderstood and thought you were talking about `save`. Agreed there's no good documentation for `exec`'s parameter file.

**Comment by jtk54** [comment]
https://github.com/spinnaker/spinnaker.github.io/pull/1187

**Comment by kychoolkim** [comment]
@jtk54  Great! Thanks a lot!
