### ISSUE TITLE
Halyard Version reference (1.8) incorrect on component-sizing/$updating-java-opts

### ISSUE THREAD

**Issue by Zamyatin** [spinnaker/spinnaker.github.io#1233]
Page: [/reference/halyard/component-sizing/](https://www.spinnaker.io/reference/halyard/component-sizing/)

Feedback: Out of curiousity - The Halyard version (1.8) mentioned [here](https://www.spinnaker.io/reference/halyard/component-sizing/#updating-java_opts) doesn't seem to exist. [Github](https://github.com/spinnaker/halyard/tags) shows Halyard versions 1.16, 1.17, etc.  

Please forgive me if I'm missing something, but when I start a docker instance of `gcr.io/spinnaker-marketplace/halyard:1.16.0` and exec into the container to run `hal --version`, I get the expected `1.16.0-20190222154056`. 

I am wondering where this Halyard version 1.8 is coming from?  If not what is the correct version to reference when updating java_opts?

**Comment by dorbin** [comment]
@Zamyatin 
The 1.8 mentioned there is an as-of version; the statement is about all versions of Halyard *since* 1.8. If you need to reference a Halyard version, I would assume the current version, or the one you're using (1.16 in this case?) is the correct one. 

@ezimanyi , anything to add?

**Comment by ezimanyi** [comment]
Nope, that's correct---given how old 1.8 is, it might just make sense at this point to remove that qualifier, but it's just saying that what follows it true for any Halyard >=1.8
