### ISSUE TITLE
official working version snapshot url

### ISSUE THREAD

**Issue by rampatnaik** [spinnaker/spinnaker.github.io#1235]
Page: [/community/releases/](https://www.spinnaker.io/community/releases/)

Feedback:
there is 2 release version
 i would like to know the official working version snapshot url

**Comment by ezimanyi** [comment]
@rampatnaik: I'm not sure I understand what you mean by the working version snapshot url.  At any given time there will be a few supported versions (generally the last 3 major releases) which are listed on that page.

**Comment by rampatnaik** [comment]
I can see 
https://dl.bintray.com/spinnaker/debians
https://dl.bintray.com/spinnaker-releases/debians

which will be for official  release

**Comment by ezimanyi** [comment]
The repository for official Spinnaker releases is https://dl.bintray.com/spinnaker-releases/debians.  When deploying with Halyard (which is the recommended path) this is automatically configured for you.

**Comment by rampatnaik** [comment]
Thanks
