### ISSUE TITLE
What is Halyard?

### ISSUE THREAD

**Issue by aviv-ebates** [spinnaker/spinnaker.github.io#1277]
Page: [/setup/install/halyard/](https://www.spinnaker.io/setup/install/halyard/)

Feedback:

It's not clear what Halyard **is**, except that it has something to do with installing/managing Spinnaker.

Is it the cli I install on my personal machine, like `kubectl` and `gcloud` and `knife`, or is it a service that's part of the deployment like `logstash` and `chef` and the k8s master?

**Comment by dorbin** [comment]
@aviv-ebates it's the Spinnaker-deployment-management CLI. 
#1278

**Comment by aviv-ebates** [comment]
so, it's installed on my laptop, like `kubectl`?
The docs should explicitly say that. Assume whoever is reading the docs, especially the Getting Started docs, isn't familiar with the language and workflows used by the project/team.

**Comment by dorbin** [comment]
It *can* be installed on your laptop. It can also be installed on a VM. Or in a [container](https://www.spinnaker.io/setup/install/halyard/#install-halyard-on-docker). 

But, I hear ya. I'll create another PR to make that clearer.

**Comment by dorbin** [comment]
#1280
