### ISSUE TITLE
InstallHalyard script URL changed

### ISSUE THREAD

**Issue by dansimau** [spinnaker/spinnaker.github.io#1320]
The URL to the `InstallHalyard.sh` script has changed in:
https://github.com/spinnaker/halyard/pull/1251

Following the docs to install Spinnaker now results in a 404 when doing the curl.

**Comment by ezimanyi** [comment]
This was changed back in spinnaker/halyard#1277 to avoid breaking anyone who had automation pointing at the old URL, so the docs change is no longer necessary.  Thanks for raising the issue!
