### ISSUE TITLE
Add pubsub enable to the Google Cloud Build documentation

### ISSUE THREAD

**Issue by MichaelHudgins** [spinnaker/spinnaker.github.io#1413]
At Google Cloud Build instructions found here: https://www.spinnaker.io/setup/ci/gcb/
It appears that there is a missing instruction that 
`hal config pubsub google enable`
must be run for spinnaker to attempt to listen to the pubsub from the cloud build event.

**Comment by dorbin** [comment]
@MichaelHudgins What Spinnaker version are you running? 
There is [this section](https://www.spinnaker.io/setup/ci/gcb/#configuration-prior-to-spinnaker-114), which shows how it worked before 1.14, and which does include the hal command you lack.

**Comment by MichaelHudgins** [comment]
Currently i have upgraded to 1.14.7, but i think i was on 1.14.5 or 1.14.6 then.

**Comment by ezimanyi** [comment]
I just tested this and can confirm that you do indeed need Google pubsub enabled for this to work.  I had intended for it to not need to be configured separately, but this doesn't work if you enable GCB but not pubsub.  I think the easiest is to update the docs, which I'll do.
