### ISSUE TITLE
SIG listing feels strange under "governance"

### ISSUE THREAD

**Issue by skandragon** [spinnaker/spinnaker.github.io#1530]
It feels strange to have to navigate through Governance to get to the SIG listing.  My opinion is that SIGs are created through the process of governance, but then they are at a community level, and should be more easily found.

I'm happy to make a PR, but I know we deep link here from several places.

**Comment by dorbin** [comment]
You're right, Michael. The Doc SIG's gonna take up overall organization. This should be a part of that. 
@brian-armory 
@fifthposition

**Comment by skandragon** [comment]
OK, I'll leave the PR to you then?

**Comment by dorbin** [comment]
Yep, thanks Michael

**Comment by 317brian** [comment]
Per @robzienert:

> [The SIGs] page really should get deleted... since the community repo is the SOT for all governance stuffs.

**Comment by fifthposition** [comment]
+1 for removing duplication (repeating info across the site and any other locations), unless we are single-sourcing somehow

**Comment by 317brian** [comment]
https://github.com/spinnaker/spinnaker.github.io/pull/1598 made the Governance link point to the GH repo, so I'm closing this.
