### ISSUE TITLE
Doc doesn't describe where to put the config for halyard

### ISSUE THREAD

**Issue by dbason** [spinnaker/spinnaker.github.io#1531]
Page: [/setup/configuration/](https://www.spinnaker.io/setup/configuration/)

Feedback:
I'm trying to set this up so our kubeconfig files are stored in vault.  We currently deploy using halyard on docker.  The docs don't describe where to put the spring config server configuration in this scenario (we don't have a spinnaker.yml for a halyard deployment).  I've tried a few permutations but keep getting `Config Server repository not configured for resource`

**Comment by dorbin** [comment]
@fifthposition
