### ISSUE TITLE
API

### ISSUE THREAD

**Issue by LALITTUTY108** [spinnaker/spinnaker.github.io#1534]
Page: [/guides/runbooks/api-rate-limiting/](https://www.spinnaker.io/guides/runbooks/api-rate-limiting/)

Feedback:A=B+C+E+F=128

**Comment by LALITTUTY108** [comment]
A=B+C+E+F+G(1)=128

**Comment by LALITTUTY108** [comment]
A=B+C+G(1)=128

**Comment by LALITTUTY108** [comment]
a=b.c.g(1)=3

**Comment by LALITTUTY108** [comment]
a=b.c.g(i)=3

**Comment by LALITTUTY108** [comment]
a+b*c=128

**Comment by LALITTUTY108** [comment]
/*/*MADHUBALA*/*/*=128

**Comment by plumpy** [comment]
¯\\_(ツ)_/¯
