### ISSUE TITLE
URL for linux and MacOS not working

### ISSUE THREAD

**Issue by GMafra** [spinnaker/spinnaker.github.io#1540]
Page: [/setup/spin/](https://www.spinnaker.io/setup/spin/)

Feedback:

**Comment by dorbin** [comment]
@GMafra , are you referring to the `curl` commands?  I just tested and they "work on my machine." :)

Can you provide more detail about what's happening. What environment are you running it in (like, Terminal on a Mac), and what error message are you gettting?

**Comment by GMafra** [comment]
Sorry for the lack of Info!

I'm running on my MacOS running iTerm2 the command to download the binaries:
`curl -LO https://storage.googleapis.com/spinnaker-artifacts/spin/$(curl -s https://storage.googleapis.com/spinnaker-artifacts/spin/latest)/darwin/amd64/spin
`
this is the result:
`<?xml version='1.0' encoding='UTF-8'?><Error><Code>NoSuchKey</Code><Message>The specified key does not exist.</Message><Details>No such object: spinnaker-artifacts/spin/latest)/darwin/amd64/spin</Details></Error>%`

**Comment by 317brian** [comment]
Also running MacOS (Mojave) and iTerm2. I copied the command from @GMafra's comment, and it worked for me.

**Comment by plumpy** [comment]
It looks like you probably aren't using `bash`? The `$()` command substitution didn't seem to work...

**Comment by 317brian** [comment]
Hi @GMafra, were you able to get this working by using `bash` instead?

**Comment by 317brian** [comment]
Ping one more time @GMafra

**Comment by GMafra** [comment]
Hi Brian, sorry for the late response, Yes, it worked with bash, thanks!

**Comment by markhicken** [comment]
`zsh` being the default shell on Mac now, we should probably still fix the page by removing the slashes.

**Comment by PClmnt** [comment]
Yea i've just ran into this same problem using zsh, would be good to get the docs updated.
