### ISSUE TITLE
Improvement in enabling of AWS ECS driver

### ISSUE THREAD

**Issue by aleon1220** [spinnaker/spinnaker.github.io#1563]
Page: [/setup/install/providers/aws/aws-ecs/](https://www.spinnaker.io/setup/install/providers/aws/aws-ecs/)

Feedback:
isnt necessary to run `hal config provider ecs enable` at the end of the configurations?

`hal deploy apply`

And validation step with
`hal config`

**Comment by dorbin** [comment]
I believe `hal config provider ecs enable` _is_ required. 
Any AWS folks know otherwise, for this provider? @edwinavalos ? @clareliguori ?

**Comment by aleon1220** [comment]
> I believe `hal config provider ecs enable` _is_ required.
> Any AWS folks know otherwise, for this provider? @edwinavalos ? @clareliguori ?

It is i dont know why is not mentioned. Also ECS provider requires a main AWS Provider account. 

How is the process of improving the Spinnaker Documentation?

**Comment by dorbin** [comment]
Sorry, @aleon1220 I misunderstood your original point! Without clicking through, I read "It isn't necessary," when you were actually asking "isn't it necessary?" Correct?

To answer your latest question, the process for improving the docs is about the same as it is for code. Fork this repo, make the change, push, create a PR, and someone will review it. 

Would you like to take care of this, or do you want one of us frequent docs contributors to do so? 
Also, let me know if you have any further questions about the process.

Thanks!
Dave

**Comment by aleon1220** [comment]
> Sorry, @aleon1220 I misunderstood your original point! Without clicking through, I read "It isn't necessary," when you were actually asking "isn't it necessary?" Correct?
> 
> To answer your latest question, the process for improving the docs is about the same as it is for code. Fork this repo, make the change, push, create a PR, and someone will review it.
> 
> Would you like to take care of this, or do you want one of us frequent docs contributors to do so?
> Also, let me know if you have any further questions about the process.
> 
> Thanks!
> Dave

thanks. I have create the PR https://github.com/spinnaker/spinnaker.github.io/pull/1601

**Comment by clareliguori** [comment]
This is now resolved in the docs, thanks @aleon1220!
https://www.spinnaker.io/setup/install/providers/aws/aws-ecs/#enable-ecs-provider
