### ISSUE TITLE
$GCP_PROJECT should be $GCP_TEST in HALYARD_SA_EMAIL

### ISSUE THREAD

**Issue by vijay-sapient** [spinnaker/spinnaker.github.io#1594]
Page: [/setup/quickstart/halyard-gke-deploy-rbac/](https://www.spinnaker.io/setup/quickstart/halyard-gke-deploy-rbac/)

Feedback:
HALYARD_SA_EMAIL=$(gcloud iam service-accounts list \
  --project=$GCP_PROJECT \
  --filter="displayName:$HALYARD_SA" \
  --format='value(email)')

The above $GCP_PROJECT should be $GCP_TEST? please verify

**Comment by dorbin** [comment]
@vijay-sapient I don't _think_ so. As the comment above that block says, 
`#Get the SA email from the Spinnaker project`
The "Spinnaker project" not the test project.
