### ISSUE TITLE
Question: Is there parity between Spinnaker versions and Kubernetes?

### ISSUE THREAD

**Issue by reubenavery** [spinnaker/spinnaker.github.io#1639]
Page: [/community/releases/versions/](https://www.spinnaker.io/community/releases/versions/)

Feedback:

Is there parity between Spinnaker versions and Kubernetes?  i.e. Spinnaker v1.14.x for Kubernetes 1.14, and upgrading to Spinnaker 1.15 when we upgrade Kubernetes to 1.15 etc

**Comment by plumpy** [comment]
The similarity in the versions is purely coincidental.
