### ISSUE TITLE
Broken link: The Spinnaker API resource is defined here.

### ISSUE THREAD

**Issue by ttomsu** [spinnaker/spinnaker.github.io#1703]
Page: [/reference/providers/kubernetes/](https://www.spinnaker.io/reference/providers/kubernetes/)

Feedback:

Broken link in this text: The Spinnaker API resource is defined [here](https://github.com/spinnaker/clouddriver/blob/master/clouddriver-kubernetes/src/main/groovy/com/netflix/spinnaker/clouddriver/kubernetes/deploy/description/servergroup/DeployKubernetesAtomicOperationDescription.groovy).

It appears to link to V1 code, so it's unclear what (if anything) it should link to in V2. @ezimanyi @maggieneterval @ethanfrogers - any suggestions?

**Comment by ethanfrogers** [comment]
I think the fix is just adding `-v1` to `clouddriver-kubernetes` and that a lot of think links on this page go away after the deprecation of V1.

**Comment by ezimanyi** [comment]
I think the file also moved within `v1` in addition to being moved to the `v1` module; the correct link is [here](https://github.com/spinnaker/clouddriver/blob/master/clouddriver-kubernetes-v1/src/main/groovy/com/netflix/spinnaker/clouddriver/kubernetes/v1/deploy/ops/servergroup/DeployKubernetesAtomicOperation.groovy).  The page that is referenced is specifically about the V1 provider so will be removed as part of the deprecation; there will be no replacement as there is already a separate page about the v2 provider [here](https://www.spinnaker.io/reference/providers/kubernetes-v2/).

**Comment by maggieneterval** [comment]
@dorbin thanks for fixing the broken link; going to close this.
