### ISSUE TITLE
Vault backend for external configuration

### ISSUE THREAD

**Issue by sagayd** [spinnaker/spinnaker.github.io#1728]
Page: [/setup/configuration/](https://www.spinnaker.io/setup/configuration/)

Feedback:
In section 'Using a Vault backend', the code block of spring.cloud.config.server.vault says
`default-key: clouddriver`. It should be defaultKey, not default-key as per the page https://cloud.spring.io/spring-cloud-static/spring-cloud-config/2.2.1.RELEASE/reference/html/#vault-backend

**Comment by 317brian** [comment]
Thanks for opening this and providing the correction @sagayd!
