### ISSUE TITLE
Typo on doc: mechanisim should be mechanism

### ISSUE THREAD

**Issue by ringanta** [spinnaker/spinnaker.github.io#1739]
Page: [/guides/user/kubernetes-v2/run-job-manifest/](https://www.spinnaker.io/guides/user/kubernetes-v2/run-job-manifest/)

Feedback:
I think there is a typo on "Artifacts are a mechanisim within Spinnaker that enables pipelines to reference resources stored in external systems". Mechanisim should be mechanism.

**Comment by dorbin** [comment]
Fixed in #1740
