### ISSUE TITLE
property not explained in pipeline-templates documentation

### ISSUE THREAD

**Issue by 0xDones** [spinnaker/spinnaker.github.io#1765]
Page: [/guides/user/pipeline/pipeline-templates/instantiate/](https://www.spinnaker.io/guides/user/pipeline/pipeline-templates/instantiate/)

Feedback:
In the [Add new stages](https://www.spinnaker.io/guides/user/pipeline/pipeline-templates/instantiate/#add-new-stages) section, what is the `config` field? It's not mentioned anywhere.  The JSON config for a `Wait` stage looks like this: 
```json
    {
      "name": "Wait",
      "refId": "3",
      "requisiteStageRefIds": [
        "1"
      ],
      "restrictExecutionDuringTimeWindow": false,
      "sendNotifications": true,
      "stageEnabled": {
        "type": "expression"
      },
      "type": "wait",
      "waitTime": 30
    }
```

**Comment by louisjimenez** [comment]
Check out the [V2StageDefinition](https://github.com/spinnaker/orca/blob/master/orca-pipelinetemplate/src/main/java/com/netflix/spinnaker/orca/pipelinetemplate/v2schema/model/V2StageDefinition.java#L38) used by pipeline templates. The config houses the configuration that is specific to the wait stage.

**Comment by 0xDones** [comment]
Thanks for pointing out, but as a suggestion, I would say that I don't think every user will drill down the code looking for answers, specially those who are not familiar with Java (like me).
