### ISSUE TITLE
what is $context

### ISSUE THREAD

**Issue by xgeoff** [spinnaker/spinnaker.github.io#1805]
Page: [/setup/install/providers/kubernetes-v2/](https://www.spinnaker.io/setup/install/providers/kubernetes-v2/)

Feedback: in your docs you refer to $context but you never state what this is? Is it a value from my Google account? Is it something that should be used as is? what is this thing?

**Comment by dorbin** [comment]
It's defined a few lines above where it's referenced.

```
CONTEXT=$(kubectl config current-context)

hal config provider kubernetes account add my-k8s-v2-account \
    --provider-version v2 \
    --context $CONTEXT
```

So its value is the result of `kubectl config current-context` run against your cluster.

I'm closing this issue, as answered, but feel free to reopen if you need more information, @xgeoff .
