### ISSUE TITLE
Add references to Kleat-based configuration

### ISSUE THREAD

**Issue by dorbin** [spinnaker/spinnaker.github.io#1877]
[Kleat]() is considered alpha. We want to let people try it out. 
Add references from hal documentation to kleat docs.

**Comment by aimeeu** [comment]
The Kleat [docs](https://github.com/spinnaker/kleat/blob/master/docs/docs.md) are generated from code, so this should involve updating the protobuf files, right?

**Comment by dorbin** [comment]
@aimeeu , yes, to edit the documentation itself. This issue is just to link to that doc from Halyard documentation.

**Comment by dorbin** [comment]
Fixed in #1901
