### ISSUE TITLE
apache2 fails to start with self-signed certificate created per documentation

### ISSUE THREAD

**Issue by tomi-roam** [spinnaker/spinnaker.github.io#1879]
Page: [/setup/security/ssl/](https://www.spinnaker.io/setup/security/ssl/)

Feedback:
The instructions and command samples under "Create the server certificate(s)" create a certificate with SHA1 which fails to load on apache2 causing spin-deck to not start. Using SHA256 allows the certificate to be used and Deck to start successfully.

Current snippet:
```
 openssl x509 \
   -req \
   -days 365 \
   -in deck.csr \
   -CA ca.crt \
   -CAkey ca.key \
   -CAcreateserial \
   -out deck.crt \
   -passin pass:${CA_KEY_PASSWORD}
```

Fixed (note addition of `-sha256` parameter):
```
 openssl x509 \
   -sha256 \
   -req \
   -days 365 \
   -in deck.csr \
   -CA ca.crt \
   -CAkey ca.key \
   -CAcreateserial \
   -out deck.crt \
   -passin pass:${CA_KEY_PASSWORD}
```

Additional detail:
The pod logs for deck show the following on the failure:
```
AH00558: apache2: Could not reliably determine the server's fully qualified domain name, using 192.168.0.4. Set the 'ServerName' directive globally to suppress this message
Action '-D FOREGROUND' failed.
The Apache error log may have more information.
```

Digging deeper and viewing apache logs (`/var/log/apache2/error.log`) shows errors similar to:
```
[Wed Jun 17 15:42:13.521938 2020] [ssl:emerg] [pid 119:tid 139878231946368] AH02562: Failed to configure certificate 192.168.192.6:9000:0 (with chain), check /somepatch/.hal/default/staging/dependencies/782294347-deck.crt
[Wed Jun 17 15:42:13.522005 2020] [ssl:emerg] [pid 119:tid 139878231946368] SSL Library Error: error:140AB18E:SSL routines:SSL_CTX_use_certificate:ca md too weak
```

**Comment by 317brian** [comment]
Oh shoot, this is my bad. Someone else filed a similar issue too, and I said I would make a PR to fix it.

Thank you for opening this! You can make a PR to fix it, or I can do it now so I don't drop the ball again @tomi-roam
