### ISSUE TITLE
affinty documentation is missing for halyard custom configuration

### ISSUE THREAD

**Issue by shubhamc183** [spinnaker/spinnaker.github.io#1912]
`affinity` configuration missing in Tweakable Service Settings under reference/halyard/custom/

**Comment by dorbin** [comment]
@perek, would you be willing to update the docs referenced here, based on the feature you added in https://github.com/spinnaker/halyard/pull/1273? Thanks!

**Comment by perek** [comment]
Hi Dave! I am on summer vacation til end of july, I could see if I can grab some time then!

**Comment by shubhamc183** [comment]
@dorbin can I send a PR?

**Comment by dorbin** [comment]
@shubhamc183 , yes absolutely!
