### ISSUE TITLE
Plugin creation page is empty

### ISSUE THREAD

**Issue by AugustasV** [spinnaker/spinnaker.github.io#1925]
Page: [/guides/developer/plugin-creators/](https://www.spinnaker.io/guides/developer/plugin-creators/)

Feedback: Plugin creation guide page is empty. Step by step guide should be created (screenshots and code snippets would be nice)

**Comment by dorbin** [comment]
@AugustasV , the guide is [there](https://spinnaker.io/guides/developer/plugin-creators/overview/), but the page at that path doesn't have links to the several documents.
