### ISSUE TITLE
${ACCOUNT_NAME}

### ISSUE THREAD

**Issue by ximbal** [spinnaker/spinnaker.github.io#195]
Page: /setup/providers/aws/

Feedback:

The ${ACCOUNT_NAME} is confusing, I've spent 45 minutes figuring out how and which account name, 2 things are missing (2 notes).
1. Account Name is only important in the spinnaker context, it has nothing to do with AWS.
2. Account Name IS CASE SENSITIVE and only likes SMALLCAPS!!!!!!.

${ACCOUNT_ID} however is relevant to AWS.
Cheers

**Comment by skim1420** [comment]
https://github.com/spinnaker/spinnaker.github.io/pull/198
