### ISSUE TITLE
Helm artifacts docs is missing in Configure Artifacts

### ISSUE THREAD

**Issue by shubhamc183** [spinnaker/spinnaker.github.io#1994]
In /setup/artifacts/ `Helm` artifact configuration is missing.

Helm configuration via the `hal` command is [implemented](https://spinnaker.io/reference/halyard/commands/#hal-config-artifact-helm). 

Can I send a PR on the configuration of the helm artifact?

**Comment by dorbin** [comment]
@shubhamc183 , yes please do! Thanks!
