### ISSUE TITLE
setup docs - storage section links redirect back to opening page

### ISSUE THREAD

**Issue by camilosantana** [spinnaker/spinnaker.github.io#203]
ref: https://www.spinnaker.io/setup/install/storage/

## Issue
clicking any of the following links:

- Azure Storage
- Google Cloud Storage
- Redis
- S3

will go to https://www.spinnaker.io/setup/storage/`{{ item abbreviation }}`

which will then immediately redirect you to https://www.spinnaker.io/

## Expected Behaviour

clicking link will take you to respective page on configuring storage.

**Comment by ttomsu** [comment]
This was my fault - invalid forwarding rules in our CDN. Should be fixed now.
