### ISSUE TITLE
S3 Storage Setting Missing ENVAR

### ISSUE THREAD

**Issue by aushafy** [spinnaker/spinnaker.github.io#2036]
Page: [/setup/install/storage/s3/](https://www.spinnaker.io/setup/install/storage/s3/)

Feedback:
I think there is missing something about ENV VAR of S3 Storage Setting example. it should be:

> hal config storage s3 edit \
>     --access-key-id $YOUR_ACCESS_KEY_ID \
>     --secret-access-key $YOUR_SECRET_KEY \
>     --region $REGION

**Comment by dorbin** [comment]
Hi, @aushafy, yeah it looks like that's the case. Thanks for pointing this out!
Any chance you can create a PR on this repo that adds that?

**Comment by aushafy** [comment]
well .. I would to create PR
