### ISSUE TITLE
Page Not Found - https://spinnaker.io/guides/tutorials/codelabs/gcp-kubernetes-source-to-prod/

### ISSUE THREAD

**Issue by bharatmicrosystems** [spinnaker/spinnaker.github.io#2051]
### Issue Summary:
When I click on Continuous Delivery with Containers on GCP from the Demo Guide on Spinnaker I get a page not found.

**Comment by dorbin** [comment]
Hi, Gaurav, can you tell me the page you were on when you clicked the link? Thanks!

**Comment by dorbin** [comment]
@bharatmicrosystems , I'm guessing you clicked on the link in the left-nav. I've updated that in PR #2102.

**Comment by bharatmicrosystems** [comment]
Yes @dorbin. Thanks for taking this up
