### ISSUE TITLE
Typo: Github -> should be Git

### ISSUE THREAD

**Issue by dperezro** [spinnaker/spinnaker.github.io#2078]
Page: [/reference/artifacts-with-artifactsrewrite/types/git-repo/](https://www.spinnaker.io/reference/artifacts-with-artifactsrewrite/types/git-repo/)

Feedback: Typo: Github -> should be Git

**Comment by dorbin** [comment]
Hi, @dperezro, thanks for the issue. 
That file has 7 occurrences of "github," including case variations and not including TOC and footer. Which one are you referring to? Or are you saying all occurrences of "github" should be "git"?

**Comment by dperezro** [comment]
Hello @dorbin . These are the changes https://github.com/spinnaker/spinnaker.github.io/pull/2079
