### ISSUE TITLE
AWS Settings in deck explanation

### ISSUE THREAD

**Issue by seong-chang-ah** [spinnaker/spinnaker.github.io#2091]
Page: [/setup/features/aws-launch-templates/](https://www.spinnaker.io/setup/features/aws-launch-templates/)

Feedback:

Hello. I'm currently trying to enable launch templates as noted in the docs above.

However, when I'm following the doc for the "New to AWS" section (particularly step 3), the instructions are unclear on if I'm supposed to provide the settings in "deck-local.yml" or somewhere else.

It doesn't look like a valid json so I'm assuming it needs to be inside one of the YAML files... and my next guess was deck-local.yml but I'd like to be sure before moving forward.

Can this step (same for "Current AWS User" step 5) be edited to be clearer and easier to understand by the reader?

Thank you very much!

**Comment by 317brian** [comment]
Closing this since 2098 resolves it for 1.23. 1.24 will require changes the mentioned in https://github.com/spinnaker/spinnaker.github.io/issues/2099
