### ISSUE TITLE
spinnaker semantic version to micro-service versions

### ISSUE THREAD

**Issue by TheDigitalNinja** [spinnaker/spinnaker.github.io#219]
Page: /community/releases/versions/1-0-0-changelog

Feedback:

On the google blog post I read "Starting with 1.0, all new Spinnaker releases are individually versioned and follow semantic versioning" looking at the repos i'm assuming they will all still be versioned independently.

Is there documentation somewhere that links the semver to the micro-services versions? I looked around in the haylard source but I couldn't seem to find it there.

**Comment by lwander** [comment]
Are you asking how the top-level version is linked? That's described here: https://www.spinnaker.io/reference/halyard/#bill-of-materials

Or are you asking what the exact version mapping is?

**Comment by TheDigitalNinja** [comment]
Nope thats it, Can't believe I missed it.  Thanks.

**Comment by lwander** [comment]
No worries
