### ISSUE TITLE
Have one error for this command:hal config storage edit --type redis

### ISSUE THREAD

**Issue by fionaliupw** [spinnaker/spinnaker.github.io#220]
Page: /setup/storage/redis/

Feedback:Hello,When i setup storage(--type redis), i got one error. The error is as following:
Unexpected exception: java.lang.RuntimeException: Failed to
  invoke validate() on "DeploymentConfigurationValidator" for node
  "DeploymentConfiguration

I hava tried to update the Halyard,  but it don't work.  How can i solve this problem? Thank you.

**Comment by ttomsu** [comment]
This question is probably best asked in the #halyard channel of the Spinnaker chatroom: https://join.spinnaker.io

**Comment by fionaliupw** [comment]
@ttomsu Thank you very much.
