### ISSUE TITLE
App Engine Source to Prod Codelab Issues

### ISSUE THREAD

**Issue by madisona** [spinnaker/spinnaker.github.io#234]
Page: /guides/tutorials/codelabs/appengine-source-to-prod/

Feedback: The codelab is very helpful in showcasing awesome functionality.  I had 2 issues though.

- the step to set `hal config version edit --version 0.3.0` caused the `hal deploy apply` step to not work. I believe I used version 1.0.1 to get it to work. There were other messages that said version 0.3.0 was not supported
- I had trouble with the `github webhook`.  I copy & pasted the network settings and double checked the IP Addresses, but github said it couldn't talk with the server. I'm not sure if it was GCP networking issues, or even where to begin debugging at which step the failure was.

**Comment by danielpeach** [comment]
Thanks - I'll update the docs.

With respect to the webhook, it looks like Github added a second source range for the webhook since I wrote the codelab (`192.30.252.0/22` and `185.199.108.0/22`, listed [here](https://help.github.com/articles/github-s-ip-addresses/)). Try adding both to your firewall rule.

The codelab assumes you're running Halyard on a GCE VM - I would double check that your VM and firewall rule were set up according to the codelab.

**Comment by madisona** [comment]
Hi @danielpeach - thanks for the follow up. I saw that an added the other range and the webhook still doesn't work.

In fact, I carefully started the tutorial all over again with a brand new GCP project, carefully following each step and am still having the same issue. Here is what my configuration looks like for the VM, Firewall rules, and Github Webhook.

**VM Settings**
![screen shot 2017-06-15 at 8 56 30 am](https://user-images.githubusercontent.com/426479/27184736-9ffc07ce-51a8-11e7-8dc8-b919cf6c502a.png)

**Firewall Rule**
![screen shot 2017-06-15 at 8 57 57 am](https://user-images.githubusercontent.com/426479/27184781-c047ccca-51a8-11e7-8533-520374c5d7b8.png)

**Github Webhook**
![screen shot 2017-06-15 at 8 52 24 am](https://user-images.githubusercontent.com/426479/27184795-cd8abc9e-51a8-11e7-9c75-fdaae5450e5d.png)


I still get the message from github `We couldn’t deliver this payload: Couldn't connect to server`

**Comment by danielpeach** [comment]
I was able to reproduce this.

Run the following:

```
echo "host: 0.0.0.0" | tee ~/.hal/default/service-settings/echo.yml
sudo hal deploy apply
```

**Comment by madisona** [comment]
@danielpeach oh nice, thank you.. now the webhook is working!

before I ran the command I opened the echo.yml file and it appeared to already have that `host: 0.0.0.0` in it. I ran your commands anyways and now things are good.


If you're looking to clean up a few other parts of the tutorial, here are just a couple other very minor things I noticed.

- The `New Application` screen looks slightly different than the current screen shot (you don't set an `account` yet on the first page. 
- At the `Pipeline Creation` step, the tooltip isn't `New`, it is now `Create Pipeline or Strategy`
- At the `Webhook Trigger` section, to be consistent with other areas, step 1 should be to click `Add Trigger`

Thanks again for this fantastic codelab!

**Comment by danielpeach** [comment]
Great, thanks - I've updated the codelab so that it works properly now. 

The screenshots will have to be updated periodically as the UI drifts - I'll be sure to include your suggestions.

**Comment by sivaprf** [comment]
I get the following error when i run the following command: Any idea why?
hal config provider appengine account add my-appengine-account --project $GCP-PROJECT-ID
+ Get current deployment
  Success
- Add the my-appengine-account account
  Failure
Problems in default.provider.appengine.my-appengine-account:
! **ERROR Failed to connect to appengine Admin API: 403 Forbidden**
{
  "code" : 403,
  "errors" : [ {
    "domain" : "global",
    "message" : "Operation not allowed",
    "reason" : "forbidden"
  } ],
  "message" : "Operation not allowed",
  **"status" : "PERMISSION_DENIED"**
}.

- Failed to add account my-appengine-account for provider
  appengine.

**Comment by danielpeach** [comment]
The command you've provided will work only if the application default credentials for the machine that's running Halyard have access to the App Engine Admin API.

I would verify the following:
- That Halyard is running on a machine with application default credentials (e.g., on a GCE VM).
- That those application default credentials have access to the App Engine Admin API.

If you're still seeing a problem, could you please open a new issue? This seems unrelated to the original issue here.

Thanks.

**Comment by timini** [comment]
Hi I have spinnaker deployed on GCE using the instructions here
https://github.com/GoogleCloudPlatform/spinnaker-deploymentmanager

I have found the account for the compute instance hosting spinnaker and have added the App Engine Admin API role on to that account on the IAMs page.

I am still receiving the 403 error
