### ISSUE TITLE
Openshift V3 support?

### ISSUE THREAD

**Issue by NaranKPatel** [spinnaker/spinnaker.github.io#235]
Page: /setup/install/providers/

Feedback: Please can you add Openshift V3 support? It's managed Kubernetes, so potentially a fair amount of re-use of existing native Kubernetes and Google Compute Engine integrations I would hope?

**Comment by lwander** [comment]
This is an entire provider integration, and is a lot of work. Please file a feature request in https://github.com/spinnaker/spinnaker/issues.
