### ISSUE TITLE
Public Spinnaker on GKE needed fixes

### ISSUE THREAD

**Issue by skim1420** [spinnaker/spinnaker.github.io#239]
Page: /setup/quickstart/halyard-gke-public/

Feedback:

For creating the client ID, the authorized redirect URLs need to match with the FQDN being set up further below.

The "navigate to.." instructions at the bottom shouldn't specify port 9000, since we're using port 80.

**Comment by lwander** [comment]
Please read the caption under the client ID creation: https://www.spinnaker.io/setup/quickstart/halyard-gke-public/#part-1-configuring-authentication

**Comment by lwander** [comment]
https://github.com/spinnaker/spinnaker.github.io/blob/master/setup/quickstart/halyard-gke-public/index.md

**Comment by lwander** [comment]
Sorry, meant to link to https://github.com/spinnaker/spinnaker.github.io/commit/cac7fbfb309347085a97392c036931593a41d0bb
