### ISSUE TITLE
step create-a-spinnaker-application is not possible

### ISSUE THREAD

**Issue by Simon-Ince** [spinnaker/spinnaker.github.io#252]
Page: /guides/tutorials/codelabs/gcp-kubernetes-source-to-prod/

Feedback: The section under https://www.spinnaker.io/guides/tutorials/codelabs/gcp-kubernetes-source-to-prod/#create-a-spinnaker-application you are asked to "Click in the Accounts field and choose “my-kubernetes-account”.", but this field does not exsit, the screen I see on this section is as follows:

![Image of error](http://i.imgur.com/HpOQdaH.png)

**Comment by ttomsu** [comment]
Your screenshot did not come through. You can include it in this PR directly - that may be the easiest.

**Comment by lwander** [comment]
Can you provide more context? How did you setup spinnaker? Did you see any errors/warnings in the process?

**Comment by skim1420** [comment]
That dialog has been updated to not display the accounts field if there is only one account configured in Spinnaker. We need to update the screenshot.

**Comment by skim1420** [comment]
My mistake, the screenshot has been updated. Closing.
