### ISSUE TITLE
Out of date commands on Google Groups authorization doc

### ISSUE THREAD

**Issue by dgpc** [spinnaker/spinnaker.github.io#259]
Page: /setup/security/authorization/google-groups/

Feedback:

The doc says to run:

hal config security roles provider google edit \
    --admin-username $ADMIN \
    --credentials-path $CREDENTIALS \
    --domain $DOMAIN

But the correct command is:

hal config security **authz** google edit \
    --admin-username $ADMIN \
    --**credential-path** $CREDENTIALS \
    --domain $DOMAIN

**Comment by ttomsu** [comment]
Thank you!
