### ISSUE TITLE
URL blocked by Google corp SSO in GCP codelab

### ISSUE THREAD

**Issue by nschuc** [spinnaker/spinnaker.github.io#291]
Page: /guides/tutorials/codelabs/gcp-kubernetes-source-to-prod/

Feedback:
The link to delete the deployment is blocked by a Google corp SSO page (I'm guessing it's the URL to the internal container engine provisioning tool): https://pantheon.corp.google.com/deployments/details/spinnaker-cd-codelab

https://www.spinnaker.io/guides/tutorials/codelabs/gcp-kubernetes-source-to-prod/#delete-the-cloud-launcher-deployment

**Comment by duftler** [comment]
Thanks.
