### ISSUE TITLE
Problem adding Account

### ISSUE THREAD

**Issue by ramvilas619** [spinnaker/spinnaker.github.io#296]
Hi I am getting a warning while trying to add an account while configuring spinnaker . Could you please help me resolve this.

Problems in default.provider.aws.my-aws-account:
- WARNING No validation for the AWS provider has been
  implemented.

**Comment by ttomsu** [comment]
I think that just means there is no validator implemented. Your settings could be right or wrong, we just don't have the code in place to tell you which. Is that right, @lwander?

**Comment by lwander** [comment]
Yup that's exactly right, thanks @ttomsu

**Comment by ghost** [comment]
how'd you solve this? Because I'm encountering the same.

**Comment by lwander** [comment]
This isn't an error, it's just a warning. It doesn't stop you from making edits or deploying.
