### ISSUE TITLE
Questions on how to start Spinnaker development?

### ISSUE THREAD

**Issue by lettrung99** [spinnaker/spinnaker.github.io#313]
Page: /community/

Feedback: Hello,
I am interested in making additional changes, i.e:  creating additional stages on Spinnaker.  Could you point me to how to setup and go about the implementation?

I found this guide: https://www.spinnaker.io/guides/developer/new-stage/
but it seems incomplete as well.

Thanks.

**Comment by skim1420** [comment]
Can you please post any specific questions (e.g. as to what's missing in the guide) in the slack #dev channel?
