### ISSUE TITLE
Accounts field missing

### ISSUE THREAD

**Issue by sivaprf** [spinnaker/spinnaker.github.io#318]
Page: /guides/tutorials/codelabs/bake-and-deploy-pipeline/

Feedback: I do not see the Accounts field as described in the above page. I followed the spinnaker installation here- https://www.spinnaker.io/guides/tutorials/codelabs/appengine-source-to-prod/ 

![image](https://user-images.githubusercontent.com/10763637/29384457-0282bb98-8289-11e7-8fdc-9a3835cb8837.png)

**Comment by skim1420** [comment]
Hi, the account field no longer appears if there is only one account configured. We should make that more clear in the codelab, but in the meanwhile feel free to ignore.

**Comment by skim1420** [comment]
Please close this issue if resolved, thanks.

**Comment by skim1420** [comment]
Created https://github.com/spinnaker/spinnaker.github.io/issues/321
