### ISSUE TITLE
Update application permissions screenshot

### ISSUE THREAD

**Issue by skim1420** [spinnaker/spinnaker.github.io#320]
https://www.spinnaker.io/setup/security/authorization/#applications still has old style Group Memberships, rather than the updated Permissions with read/write.

**Comment by stewchen** [comment]
@dorbin Here's a screenshot of the updated Permissions!
![permissions](https://user-images.githubusercontent.com/3814687/35170185-4e8eb018-fd2d-11e7-9b78-d19afd7d2b30.png)

**Comment by dorbin** [comment]
#511
