### ISSUE TITLE
Problems with bake on custom networks

### ISSUE THREAD

**Issue by oscarAmarello** [spinnaker/spinnaker.github.io#323]
I have a project on GCP, and im not being able to do the codelabs, because we are using custom networks, and not the default, im getting the following entry on the log for the bake stage:

==> googlecompute: Checking image does not exist...
==> googlecompute: Creating temporary SSH key for instance...
==> googlecompute: Using image: ubuntu-1404-trusty-v20170818
==> googlecompute: Creating instance...
    googlecompute: Loading zone: us-central1-a
    googlecompute: Loading machine type: n1-standard-1
    googlecompute: Loading network: my-custom-network
==> googlecompute: Error creating instance: a subnetwork must be specified
Build 'googlecompute' errored: Error creating instance: a subnetwork must be specified

==> Some builds didn't complete successfully and had errors:
--> googlecompute: Error creating instance: a subnetwork must be specified

==> Builds finished but no artifacts were created.

**Comment by duftler** [comment]
The default gce packer template allows for the subnet to be passed as `gce_subnetwork`: https://github.com/spinnaker/rosco/blob/master/rosco-web/config/packer/gce.json#L8

You can specify that attribute, as well as any others defined in the user variables section of your packer template, via the 'Extended Attributes' control under the 'Advanced Options` section in the bake stage configuration:

![image](https://user-images.githubusercontent.com/8437718/29565517-49140190-8714-11e7-96d3-a02a95a3815c.png)

**Comment by oscarAmarello** [comment]
Thanks duftler, this made my day. is there any kind of index or something where I can refer to in order to consult specific configurations for the other components too?

**Comment by duftler** [comment]
The packer templates we include by default can really be thought of as
placeholders. But you can consult each one here (
https://github.com/spinnaker/rosco/tree/master/rosco-web/config/packer) to
see what user variables they define.

You can also define your own custom packer templates and specify that
template in the same Advanced Options section.
