### ISSUE TITLE
guides is blank

### ISSUE THREAD

**Issue by stevemcghee** [spinnaker/spinnaker.github.io#350]
Page: /guides/

Feedback:  no content on page.

**Comment by dorbin** [comment]
@stevemcghee , do you mean spinnaker.io/guides/? Could you share a screenshot?

**Comment by ttomsu** [comment]
Click the `Videos` and `Codelab` links on the left.

**Comment by stevemcghee** [comment]
aha.  perhaps that (see links in the menu on the left) could be added to the body of the article.

**Comment by dorbin** [comment]
Yes I've been thinking that, and it's in my plans for doc improvements. 
But just to be clear, before you click Videos or Codelabs, you're just in /guides/, do you see the intro paragraph?
