### ISSUE TITLE
Unable to complete halyard-gke-public setup - 401 "User's info does not have all required fields"

### ISSUE THREAD

**Issue by rosskevin** [spinnaker/spinnaker.github.io#363]
Page: /setup/quickstart/halyard-gke-public/

## Feedback:

Unable to complete halyard-gke-public setup:

> If you’re greeted with the following login screen on localhost:9000 you’re all set! 

Yay! made it here.

> Make sure you can successfully login before continuing, however.

Uh, that didn't work.  Now what?

```
{
  "error": "Unauthorized",
  "message": "Authentication Failed: User's info does not have all required fields.",
  "status": 401,
  "timestamp": 1506985726074
}
```

[SO question](https://stackoverflow.com/questions/46534989/spinnaker-gke-oauth-users-info-does-not-have-all-required-fields?noredirect=1#comment80024714_46534989)

----

I'm trying to get my spinnaker interface authenticated using this tutorial:
https://www.spinnaker.io/setup/quickstart/halyard-gke-public/

Prior to the tutorial, spinnaker was confirmed up and running on `http://localhost:9000`.  After editing/applying/enabling the google security, I try the login and successfully am challenged with a google login screen.  Upon completing the challenge and I am redirected as expected to `http://localhost:8084/login`, though I receive the following error:

    {
      "error": "Unauthorized",
      "message": "Authentication Failed: User's info does not have all required fields.",
      "status": 401,
      "timestamp": 1506985726074
    }

Here is a log of my setup steps:

    kross@halyard:~$ hal config security authn oauth2 edit --provider google \
    >     --client-id $CLIENT_ID \
    >     --client-secret $CLIENT_SECRET \
    >     --user-info-requirements hd=$DOMAIN
    + Get current deployment
      Success
    + Get authentication settings
      Success
    + Edit oauth2 authentication settings
      Success
    Problems in default.security:
    - WARNING Your UI or API domain does not have override base URLs
      set even though your Spinnaker deployment is a Distributed deployment on a
      remote cloud provider. As a result, you will need to open SSH tunnels against
      that deployment to access Spinnaker.
    ? We recommend that you instead configure an authentication
      mechanism (OAuth2, SAML2, or x509) to make it easier to access Spinnaker
      securely, and then register the intended Domain and IP addresses that your
      publicly facing services will be using.
    
    + Successfully edited oauth2 method.
    kross@halyard:~$ hal config security authn oauth2 enable
    + Get current deployment
      Success
    + Edit oauth2 authentication settings
      Success
    Problems in default.security:
    - WARNING Your UI or API domain does not have override base URLs
      set even though your Spinnaker deployment is a Distributed deployment on a
      remote cloud provider. As a result, you will need to open SSH tunnels against
      that deployment to access Spinnaker.
    ? We recommend that you instead configure an authentication
      mechanism (OAuth2, SAML2, or x509) to make it easier to access Spinnaker
      securely, and then register the intended Domain and IP addresses that your
      publicly facing services will be using.
    
    + Successfully enabled oauth2

    kross@halyard:~$ hal  deploy apply
    + Get current deployment
      Success
    + Apply deployment
      Success
    + Deploy spin-clouddriver
      Success
    + Deploy spin-front50
      Success
    + Deploy spin-orca
      Success
    + Deploy spin-deck
      Success
    + Deploy spin-echo
      Success
    + Deploy spin-gate
      Success
    + Deploy spin-igor
      Success
    + Deploy spin-rosco
      Success
    Problems in default.security:
    - WARNING Your UI or API domain does not have override base URLs
      set even though your Spinnaker deployment is a Distributed deployment on a
      remote cloud provider. As a result, you will need to open SSH tunnels against
      that deployment to access Spinnaker.
    ? We recommend that you instead configure an authentication
      mechanism (OAuth2, SAML2, or x509) to make it easier to access Spinnaker
      securely, and then register the intended Domain and IP addresses that your
      publicly facing services will be using.

I'm not quite sure what to do with this.  It seems I am authentic, yet for some reason the required user fields are not allowed in the interaction.

I have reviewed [spinnaker's authentication setup](https://www.spinnaker.io/setup/security/authentication/) as well and repeatedly made a few changes and tested with a fresh incognito browser, yet no change.

Since the [`google` provider is a packaged OAuth 2 provider with spinnaker](https://www.spinnaker.io/setup/security/authentication/oauth/), I'm confused as to what further configuration would be necessary, as I am not "bringing my own provider".

Where can I start looking next?  Any references/pointers to documentation?

**Comment by ttomsu** [comment]
[SO answer](https://stackoverflow.com/a/46693410/5569046), copy/pasted below:

The problem is the --user-info-requirements hd=$DOMAIN argument. This is (generally) only needed if you're using a G Suite/Google Apps for Work account as your OAuth identity provider - it restricts login to only users in your domain. Otherwise, anyone with a valid @gmail account would be able login.

**Comment by rosskevin** [comment]
@ttomsu please don't close this, I am a G Suite/Google Apps user and I DO want to restrict it to my domain.

So if the problem is `--user-info-requirements hd=$DOMAIN`, and I need it, what is the solution?

Are you saying the value for `$DOMAIN` is incorrect?

**Comment by ttomsu** [comment]
What is the domain you've specified and what email address are you trying to login with?

**Comment by rosskevin** [comment]
Thanks @ttomsu - I checked my bash history, and I didn't try with a FQDN, only the name without `.com`.  Trying that now, as it seems like an obvious mistake on my part.

**Comment by ttomsu** [comment]
:+1:

**Comment by rosskevin** [comment]
Confirmed - domain needed is FQDN and the above error is what one receives when the domain is invalid.  I'm all set now.

**Comment by satnir** [comment]
I am a GSuite user and used right FQDN still i have same issue with Spinnaker 1.8.5 on gke1.9.7. Any idea please?
