### ISSUE TITLE
Docker image issue for Spinnaker

### ISSUE THREAD

**Issue by sujaydevops1** [spinnaker/spinnaker.github.io#372]
Page: /setup/install/halyard/

Feedback:

THis is broken docker image : docker pull gcr.io/spinnaker-marketplace/halyard:stable

I tried installed and failed at hal deploy apply - saying its not OS - Ubuntu 14.04

**Comment by sujaydevops1** [comment]
Please respond if anyone luck with install using docker pull gcr.io/spinnaker-marketplace/halyard:stable

Thansk!

**Comment by lwander** [comment]
you can't install local debian packages into a docker container, you need to use it to manage a remote k8s env
