### ISSUE TITLE
Slack set up instructions

### ISSUE THREAD

**Issue by mononokehime** [spinnaker/spinnaker.github.io#377]
Page: /setup/features/notifications/

Feedback:
Could the slack setup be updated to use halyard? It's much simpler and safer:
hal config notification slack enable
hal config notification slack edit --bot-name $SPINNAKER_BOT --token $TOKEN_FROM_SLACK

**Comment by dorbin** [comment]
Yep, this exists in Halyard currently, but it won't work until Spinnaker 1.5.0. Will update page accordingly. Thanks for pointing this out, @mononokehime !
