### ISSUE TITLE
Add generic list of available stages

### ISSUE THREAD

**Issue by ttomsu** [spinnaker/spinnaker.github.io#380]
Page: /concepts/

Feedback: From [chat room](https://spinnakerteam.slack.com/archives/C091CCWRJ/p1508510660000463)

Generic list of stages should go here, with pointer to provider-specific impl details.

**Comment by mdirkse** [comment]
I'd love to help out!

**Comment by dorbin** [comment]
Thanks, Maarten. 
Tag me on the PR when you're finished.
@mdirkse

**Comment by dorbin** [comment]
@mdirkse , do you have a draft list? What do you think will be the stages?

**Comment by mdirkse** [comment]
tbh, when I said I'd like to help I meant help whoever is going to do this ;)
But I don't mind doing it myself, I just need a couple of days to get started.

**Comment by dorbin** [comment]
Closing this as obsolete.

See #816 #840 #854 #907 

Thanks, @nhayes !
