### ISSUE TITLE
Failed to edit persistent storage. Task killed because it was   taking too long.

### ISSUE THREAD

**Issue by wholegale39** [spinnaker/spinnaker.github.io#405]
Page: /setup/storage/redis/

Feedback:
@ubuntu:~$ hal config storage edit --type redis
+ Get current deployment
  Success
+ Get persistent storage settings
  Success
/ Edit persistent storage settings
  Timed out
Problems in Global:
! ERROR Unexpected exception:
  DaemonTaskInterrupted(interruptedTime=1510553352544, message=Task interrupted
  without cause at Sun Nov 12 22:09:12 PST 2017)

- Failed to edit persistent storage. Task killed because it was
  taking too long.

**Comment by dorbin** [comment]
@wholegale39 , this is probably an example of [this](https://www.spinnaker.io/setup/quickstart/faq/#halyard-times-out-during-a-config-change).

If that doesn't help, can you please open a new issue in [spinnaker/spinnaker](https://github.com/spinnaker/spinnaker/issues) or [spinnaker/halyard](https://github.com/spinnaker/halyard/issues)? Thanks!
