### ISSUE TITLE
missing 'edit' in hal config storage s3

### ISSUE THREAD

**Issue by rama-arun** [spinnaker/spinnaker.github.io#425]
Page: /setup/storage/minio/

Feedback:

echo $MINIO_SECRET_KEY | hal config storage s3 --endpoint $ENDPOINT \
should be
echo $MINIO_SECRET_KEY | hal config storage s3 **edit** --endpoint $ENDPOINT \

**Comment by lwander** [comment]
Good catch: 

https://github.com/spinnaker/spinnaker.github.io/pull/426
