### ISSUE TITLE
Service account names don't match in example

### ISSUE THREAD

**Issue by skim1420** [spinnaker/spinnaker.github.io#439]
On the [service accounts](https://www.spinnaker.io/setup/security/authorization/service-accounts/#creating-service-accounts) page, the [Creating Service Accounts](https://www.spinnaker.io/setup/security/authorization/service-accounts/#creating-service-accounts) example creates a service account named `myApp-svc-account`, however in the [Using Service Accounts](https://www.spinnaker.io/setup/security/authorization/service-accounts/#using-service-accounts) example screenshot below that, it uses a service account of different name (`sekret-service-account@spinnaker-test.net`). They should match.

**Comment by dorbin** [comment]
@skim1420 
Obviously quicker if I just change the name in the example rather than try to re-create the screen shot. Does it append the @ spinnaker-test.net, such that can just change the exaple to `sekret-service-acct`?

**Comment by skim1420** [comment]
It doesn't append the @spinnaker-test.net.
