### ISSUE TITLE
Permissions missing from GKE quick-start

### ISSUE THREAD

**Issue by betandr** [spinnaker/spinnaker.github.io#443]
Page: /setup/quickstart/halyard-gke/

Feedback: I think the `GCS service account` section might be missing the command to give it the storage admin role, such as:
```
gcloud projects add-iam-policy-binding $PROJECT \
    --role roles/storage.admin --member serviceAccount:$SA_EMAIL
```
...in this [Downloading Credentials](https://www.spinnaker.io/setup/storage/gcs/#downloading-credentials) documentation. Following the instructions yields:
```
+ Get current deployment
  Success
+ Get persistent store
  Success
- Edit persistent store
  Failure
Problems in default.persistentStorage.gcs:
! ERROR Failed to ensure the required bucket
  "spin-f6c2f8aa-82a2-45eb-a381-30cd94899142" exists:
  com.google.api.client.googleapis.json.GoogleJsonResponseException: 403 Forbidden
{
  "code" : 403,
  "errors" : [ {
    "domain" : "global",
"message" : "gcs-service-account@cg-pov.iam.gserviceaccount.com does not have
  storage.buckets.get access to spin-f6c2f8aa-82a2-45eb-a381-30cd94899142.",
    "reason" : "forbidden"
  } ],
"message" : "gcs-service-account@cg-pov.iam.gserviceaccount.com does not have
  storage.buckets.get access to spin-f6c2f8aa-82a2-45eb-a381-30cd94899142."
}

- Failed to edit persistent store "gcs".
```

**Comment by dorbin** [comment]
@betandr , the doc you link that gives the error is /setup/storage/_gcs_/ , but the quickstart instructions you're using do include the storage.admin policy binding in [this section](https://www.spinnaker.io/setup/quickstart/halyard-gke/#set-up-credentials). Did you follow the quickstart, or did you skip over to the gcs setup at some point and try to do it there?

**Comment by betandr** [comment]
Oh you're quite right. That's odd because I followed those instructions and the service account didn't have the permissions until I used the credentials I created from other instructions worked. It's probably PEBKAC, I guess, but I raised it because somebody else mentioned it on Slack and had the same problem. I'll try to go through the instructions again and post something more appropriate if I still have an issue.

**Comment by rosskevin** [comment]
Crazy enough, I'm using a script from an old run through of a spinnaker install and I'm bumping into this.  I've re-checked to ensure I've setup permissions, re-created service accounts and keys and still bump into this.

```bash
SPINNAKER_SA=spinnaker-sa
gcloud iam service-accounts create \
    ${SPINNAKER_SA} \
    --project=${GOOGLE_CLOUD_PROJECT} \
    --display-name ${SPINNAKER_SA}

SPINNAKER_SA_EMAIL=$(gcloud iam service-accounts list \
    --project=${GOOGLE_CLOUD_PROJECT} \
    --filter="displayName:${SPINNAKER_SA}" \
    --format='value(email)')
SPINNAKER_SA_DEST=${GCP_DIR}/${SPINNAKER_SA}.json

gcloud projects add-iam-policy-binding \
    ${GOOGLE_CLOUD_PROJECT} \
    --role=roles/storage.admin \
    --member=serviceAccount:${SPINNAKER_SA_EMAIL}

gcloud projects add-iam-policy-binding \
    ${GOOGLE_CLOUD_PROJECT} \
    --role=roles/browser \
    --member=serviceAccount:${SPINNAKER_SA_EMAIL}

gcloud iam service-accounts keys create \
    ${SPINNAKER_SA_DEST} \
    --iam-account=${SPINNAKER_SA_EMAIL}

hal config storage gcs edit \
    --project ${GOOGLE_CLOUD_PROJECT} \
    --bucket spinnaker \
    --bucket-location us \
    --json-path ${SPINNAKER_SA_DEST} \
\
&& hal config storage edit --type gcs
```

If anyone has a clue, I'd sure like to know what I've scripted incorrectly. I double check in the GCP console and roles/service-account/key looks correct.

**Comment by rosskevin** [comment]
Well this is one problem - but I only added the bucket name after the generated ones continually failed:

![create_a_bucket_-_advisorintake](https://user-images.githubusercontent.com/136564/43347170-da750d18-91b9-11e8-963d-a02c5dc556ef.png)

I'll manually create/specify a unique one for now and see if I can continue.

**Comment by rosskevin** [comment]
Even with a manually created bucket, still cannot execute the hal command.

```
kross@halyard:~/setup$ hal config storage gcs edit \
>     --project ${GOOGLE_CLOUD_PROJECT} \
>     --bucket ${GOOGLE_CLOUD_PROJECT}-spinnaker \
>     --bucket-location us \
>     --json-path ${SPINNAKER_SA_DEST} \
> \
> && hal config storage edit --type gcs
+ Get current deployment
  Success
+ Get persistent store
  Success
- Edit persistent store
  Failure
Problems in default.persistentStorage:
- WARNING Your deployment will most likely fail until you configure
  and enable a persistent store.

Problems in default.persistentStorage.gcs:
! ERROR Failed to ensure the required bucket
  "my-project-unique-name-spinnaker" exists:
  com.google.api.client.googleapis.json.GoogleJsonResponseException: 403 Forbidden
{
  "code" : 403,
  "errors" : [ {
    "domain" : "global",
"message" : "spinnaker-sa@my-project-unique-name.iam.gserviceaccount.com does not have
  storage.buckets.get access to my-project-unique-name-spinnaker.",
    "reason" : "forbidden"
  } ],
"message" : "spinnaker-sa@my-project-unique-name.iam.gserviceaccount.com does not have
  storage.buckets.get access to my-project-unique-name-spinnaker."
}

- Failed to edit persistent store "gcs".
```

**Comment by sc250024** [comment]
Also having the same problem as @rosskevin but with AWS

**Comment by rosskevin** [comment]
I had an idea over the weekend. I have deleted/recreated the service account several times. I narrowed this issue to a GCP issue alone by trying to use the service account to read/write to a bucket (`gsutil config -e`). I recreated the permission problem seen with the hal command.

My theory (not confirmed yet) is the delete/recreate of the service account is the root cause, and my service account credentials of the same name are not being propagated/re-propagated...e.g. cached.  Waited over this weekend and will try tomorrow.

One way to circumvent the cache (theoretical problem) to prove this right now would be to change the service account name. I'm AFK so can't until tomorrow.

**Comment by rosskevin** [comment]
I have now confirmed the problem and a workaround.  I retried the service account I created on Friday (3 days ago) and it still yields 403 forbidden.

## Cause (GCP bug): 
Creating and deleting/recreating a service account with the same name

## Symptom
403 forbidden when using for an operation

## Workaround
Change the name of the service account var for the script, recreate, and test with:

```bash
# revoke any current credentials to be paranoid
gcloud auth revoke
# configure your new spinnaker key
gsutil config -e
# try a bucket operation
gsutil cp foo.txt gs://my-project-unique-name-spinnaker
```

It seems GCP has a credential problem when the generated email is identical.
