### ISSUE TITLE
No security group exception

### ISSUE THREAD

**Issue by geass** [spinnaker/spinnaker.github.io#472]
Hi team,

I've created a stage on my pipeline to clone a server group but while it's running, after 5 seconds, It's giving exception " Missing Security Groups" but I can see the security groups on the security groups tab and swagger. How can I solve that issue ?

best,

**Comment by dorbin** [comment]
@geass 
Can you open this same issue on [spinnaker/spinnaker](https://github.com/spinnaker/spinnaker/issues)? You've created this one in the documentation repo. :)

**Comment by mlhatfield** [comment]
@geass Did you ever open up a ticket / find a resolution to that issue? We're experiencing the same problem...
