### ISSUE TITLE
Username is used in script without validation

### ISSUE THREAD

**Issue by ocsig** [spinnaker/spinnaker.github.io#490]
`HALYARD_HOST=$USER-halyard-`date +%m%d`  `

setup/quickstart/halyard-gce.md
setup/quickstart/halyard-gke/index.md

$USER may contain invalid characters like "_" which would make the script fail. I would add a simple check/replace.

**Comment by lwander** [comment]
Good catch @ocsig - we'll do a check/replace

**Comment by lwander** [comment]
+@ezimanyi

**Comment by ezimanyi** [comment]
Fixed in https://github.com/spinnaker/spinnaker.github.io/pull/519; must have forgotten to close the issue at the time.
