### ISSUE TITLE
Infinite redirects at https://www.spinnaker.io/setup/install/environment/

### ISSUE THREAD

**Issue by DenisBY** [spinnaker/spinnaker.github.io#509]
at `Next Steps` link to [Persistent Storage](https://www.spinnaker.io/setup/install/storage/)

**Comment by lwander** [comment]
Hey @dorbin I think @ezimanyi was going to point this out as well

**Comment by lwander** [comment]
Ah and it's already fixed by @dorbin :) https://github.com/spinnaker/spinnaker.github.io/pull/508
