### ISSUE TITLE
unable to authenticate with kubernetes cluster

### ISSUE THREAD

**Issue by ramimmadi** [spinnaker/spinnaker.github.io#550]
Page: /setup/quickstart/halyard-gke-deploy-rbac/

Feedback:

I folled the document but I am getting error , stating unable to communicate with kubernetes cluster. Namespaces errors and says anonymous user error

**Comment by dorbin** [comment]
@ramimmadi , on what step in the process does the error occur? Are you on [Part 1, Configure gcloud](https://www.spinnaker.io/setup/quickstart/halyard-gke-deploy-rbac/#part-1-configure-gcloud)?

**Comment by ramimmadi** [comment]
Thank you so much for the reply.

It worked after I changed the yaml file inside the VM . It might have taken
the cache or something like that. For so long I got that error. Later just
removed the unwanted account name and ran it. It run

Regard
Ram

**Comment by dorbin** [comment]
Ok, good to know. Thanks for reporting it.
