### ISSUE TITLE
Local Debian install is not supported in the docker image

### ISSUE THREAD

**Issue by snstanton** [spinnaker/spinnaker.github.io#556]
Page: /setup/install/environment/

Feedback:

The Debian docker image supplied by the halyard setup does not work as a local installation environment.  This should be mentioned in this document, as it is confusing for a first time installation to run in to the error message that Debian is not supported.

**Comment by dorbin** [comment]
Thanks, Scott. Would you like to add a note to that page?

**Comment by lwander** [comment]
Closed by #557
