### ISSUE TITLE
Is Authorization page out of date?

### ISSUE THREAD

**Issue by rboyc** [spinnaker/spinnaker.github.io#559]
Page: /setup/security/authorization/

Feedback:
In the New Application dialog image it highlights a section called 'Group Membership'.  When I enabled authorization (using Google Groups) it displayed Permissions in this position.

**Comment by dorbin** [comment]
Hi, @rboyc , yes that page is out of date. There's an issue for it: #546 , so I'll close this one as a dupe. Thanks!
