### ISSUE TITLE
Cant access dashboard in 1.6.0

### ISSUE THREAD

**Issue by sunlove123** [spinnaker/spinnaker.github.io#586]
![spinnaker ui](https://user-images.githubusercontent.com/25791116/36586184-ca780244-18a6-11e8-8f36-b5eb32efeeed.JPG)
Page: /community/releases/versions/1-6-0-changelog

Feedback: After installing spinnaker 1.6.0 in Ubuntu 16.04, it installed all the dependencies and gets success with "hal deploy apply". Then I use "hal deploy connect" to make UI available as local host. After that when I hit on "curl localhost:9000" it gives the result "curl: (56) Recv failure: Connection reset by peer". Can you please help me to resolve this issue!!!!

**Comment by dorbin** [comment]
Hi, @sunlove123 , can you create this issue in the [spinnaker/spinnaker](https://github.com/spinnaker/spinnaker/issues) repo? Or for a possibly faster response, ask about it in our [Slack channel](https://spinnakerteam.slack.com/messages/C091CCWRJ/team/U1KCNE76Y/).

Thanks!
