### ISSUE TITLE
Editing Your Artifact Settings error

### ISSUE THREAD

**Issue by skim1420** [spinnaker/spinnaker.github.io#594]
Page: /setup/artifacts/gcs/

Feedback:

Near the bottom it clears the SERVICE_ACCOUNT_DEST env var, not sure why. Clearing this causes hal config artifact gcs account add $ARTIFACT_ACCOUNT_NAME --json-path $SERVICE_ACCOUNT_DEST to fail.

**Comment by lwander** [comment]
The instructions say to take the value from the above section -- that wasn't meant to be copy-pasted.

**Comment by skim1420** [comment]
Maybe the comment "# See Prerequisites section above" should read something like "# Set to same value from the above section"?

**Comment by dorbin** [comment]
Or make the value explicit here? Or make the comment even more obvious: "#Don't copy this. Set it to same value as above"?

**Comment by dorbin** [comment]
Resolved in #597
