### ISSUE TITLE
Add MakerBot logo

### ISSUE THREAD

**Issue by dorbin** [spinnaker/spinnaker.github.io#606]
to https://www.spinnaker.io/community/#whos-using-spinnaker

**Comment by dorbin** [comment]
@demobox FYI

**Comment by dorbin** [comment]
#613

**Comment by aglover** [comment]
Ideally, we can keep the names alphabetical; plus, we should be able to find a smaller version of the MakerBot logo. Thoughts?

**Comment by dorbin** [comment]
I've re-alphabetized, under #617. I scaled the MakerBot logo down comfortably, but CSS is autoscaling them, and this one is disproportionaltly tall, so it gets big again and loses resolution.

@sbwsg and ideas?

**Comment by dorbin** [comment]
Found the magic bit of css, #617 updated
