### ISSUE TITLE
Dependency graph / table are not showing same dependency relationships, many mismatches

### ISSUE THREAD

**Issue by kreased** [spinnaker/spinnaker.github.io#609]
Page: /reference/architecture/

Feedback:

There appear to be several mismatches between the "System Dependency Graph" diagram, and the table view. 

For example: 
- the diagram indicates Echo depends on Orca
- the table indicates Orca depends on Echo

Looking closely at it, there are a lot of discrepancies between them.
Which is correct? Are they supposed to represent the same information?

**Comment by duftler** [comment]
The table indicates that orca and echo are dependent on one another.

The table more accurately reflects the dependencies if every feature of Spinnaker is enabled, and includes dependencies relating to very low-level things like publishing events to the eventing bus or persisting configs.

The diagram is more of a conceptual overview of what spinnaker services are typically involved when performing Spinnaker operations or executing pipelines.

That said, you have a good point that we should make all of this clearer; we are working on it.

**Comment by dorbin** [comment]
#640
