### ISSUE TITLE
GKE OAuth docs suggest hd param is for access control, which contradicts the official docs

### ISSUE THREAD

**Issue by nfirvine** [spinnaker/spinnaker.github.io#611]
Page: /setup/quickstart/halyard-gke-public/

Feedback:

>  The --user-info-requirements hd=$DOMAIN is very important. Without it, any user with a valid GMail address can sign into your Spinnaker.

The Google docs on the `hd` param explicitly say *not* to rely on it for access control.

https://developers.google.com/identity/protocols/OpenIDConnect#hd-param

If this is the case, how do we ensure access?

**Comment by dorbin** [comment]
@stewchen , any thoughts on this?

**Comment by stewchen** [comment]
That `hd` authentication param pointed out in the docs is actually something entirely separate - it is a UI hint to suggest a login domain for users who are attempting to login. This is not used in our OAuth flow and not relevant to our `--user-info-requirements` authentication. If you look in the code [here](https://github.com/spinnaker/gate/blob/5ea08ec328c8f25bfa42dd7982a3ae634256991a/gate-web/src/main/groovy/com/netflix/spinnaker/gate/security/oauth2/SpinnakerUserInfoTokenServices.groovy#L79), we are relying on Spring framework to handle the authentication, and then doing the user info checks on the response fields.
