### ISSUE TITLE
Note about auth git github oauth

### ISSUE THREAD

**Issue by rafitadiaz** [spinnaker/spinnaker.github.io#621]
Page: /setup/ci/jenkins/

Feedback:
I spent some time guessing how connect the basic auth for Jenkins using the github oauth plugin. So if it's possible can you add something like this?:

Github oauth plugin:

If you are using github oauth plugin as auth provider for your jenkins installation is a also possible configure it to work with spinnaker using a github token as a password. (https://github.com/settings/tokens)
Starting in the version 0.29 the github oauth plugin also allows the authentication using the Jekins API token instead a github token.

**Comment by dorbin** [comment]
@stewchen , what say ye? If this works for you, I can add it.

**Comment by stewchen** [comment]
This looks like a good addition. @rafitadiaz did you pass in the github token as `$PASSWORD` here?
```
echo $PASSWORD | hal config ci jenkins master add my-jenkins-master \
    --address $BASEURL \
    --username $USERNAME \
    --password # password will be read from STDIN to avoid appearing
               # in your .bash_history
```

**Comment by jinagamvasubabu** [comment]
Hi @stewchen, Yes it works with Github personal access token created.

hal config ci jenkins master edit MASTER1 --address $ADDRESS/ --username $Username --password 

pass your token when its prompted.

**Comment by lwander** [comment]
That's really neat, I would definitely call that out.
