### ISSUE TITLE
No documentation for Jenkins pipeline trigger

### ISSUE THREAD

**Issue by demobox** [spinnaker/spinnaker.github.io#633]
The [Jenkins configuration](https://www.spinnaker.io/setup/ci/jenkins/) page in the documentation talks about the script execution stage, but doesn't mention the ability to use Jenkins as a trigger for a pipeline:

![707idzmohb0](https://user-images.githubusercontent.com/223702/37788558-17c3526a-2dd8-11e8-8a77-723b377b98f4.png)

**Comment by dorbin** [comment]
@nhayes 
Looks like Jenkins trigger was not included in the recent [Pipeline Triggers guide](https://www.spinnaker.io/guides/user/pipeline/triggers/). Should it be?
