### ISSUE TITLE
explanation is not finished in authorization google-group documentation

### ISSUE THREAD

**Issue by paullaleu** [spinnaker/spinnaker.github.io#653]
Page: /setup/security/authorization/google-groups/

Feedback: The document doesn't actually say what group should you put your users into, a specific name ? do you have to declare it in halyard ? how ?

**Comment by dorbin** [comment]
@paullaleu 
Sorry this issue has languished so long. 

Group names are configured, using Halyard, as described [here](https://www.spinnaker.io/setup/security/authorization/#accounts). As far as what groups you should put your users into, that's up to you. 

I'm rereading this doc now to see how I can make it clearer.

**Comment by dorbin** [comment]
#932
