### ISSUE TITLE
saml authorization help

### ISSUE THREAD

**Issue by degilq** [spinnaker/spinnaker.github.io#677]
Page: [/setup/security/authorization/saml/](https://www.spinnaker.io/setup/security/authorization/saml/)

Feedback:

hi all, please, how can reconfigure Gate’s settings attribute statement (memberOf) for other, for example "groups"

**Comment by lwander** [comment]
Hey, 

This might best be answered in our [Spinnaker Slack](https://spinnakerteam.slack.com). If you're not already a member, you can join using [this link](http://join.spinnaker.io).
