### ISSUE TITLE
spin-fiat fails with error auth.groupMembership.github.baseUrl may not be empty

### ISSUE THREAD

**Issue by rafitadiaz** [spinnaker/spinnaker.github.io#687]
Page: [/setup/security/authorization/github-teams/](https://www.spinnaker.io/setup/security/authorization/github-teams/)

Feedback:
Not sure if it's a bug or a problem with my version of halyard. (0.48)

I did as the tutorial said to configure the authz with github
```
hal config security authz github edit --accessToken xxxxxxxxxxx --organization skimhub
```
And the creation of the container failed with this error message:
```
spin-fiat 	Apr 18, 2018, 4:11:12 PM	Reason: may not be empty
spin-fiat 	Apr 18, 2018, 4:11:12 PM	Value: null
spin-fiat 	Apr 18, 2018, 4:11:12 PM	Property: auth.groupMembership.github.baseUrl
```

I solved the problem setting the baseUrl in a explicit way:

```
hal config security authz github edit --accessToken xxxxxxxxx --organization skimhub --baseUrl https://api.github.com
```

Should it set implicit for github if the param is not set?
Should this be part of the validation before deployment?

**Comment by stewchen** [comment]
Yes, this should be part of the validation, and the baseUrl should be set to https://api.github.com. The halyard section in the doc should also be updated to include the `--baseUrl` setting, and remove the `TODO`
