### ISSUE TITLE
Where do we configure `default.apiPort`

### ISSUE THREAD

**Issue by xtreme-sameer-vohra** [spinnaker/spinnaker.github.io#693]
Page: [/setup/security/authentication/x509/](https://www.spinnaker.io/setup/security/authentication/x509/)

Feedback: It is not clear from the document where this value needs to be configured ?
I don't see the value in "~/.hal/config"

**Comment by stewchen** [comment]
This value is not configurable via halyard yet, but is set on `gate-local.yml` We should call this out specifically, and link to https://github.com/spinnaker/kork/blob/master/kork-web/src/main/groovy/com/netflix/spinnaker/config/TomcatConfiguration.groovy where this value is configured via Spring. Something like:

You can move the client certificate-enabled port by modifying your `gate-local.yml` file with a port other than 8084:
```
default.apiPort: 8085
```
