### ISSUE TITLE
ECR dependency not documented

### ISSUE THREAD

**Issue by colfredstan** [spinnaker/spinnaker.github.io#708]
The ECS provider documentation (https://www.spinnaker.io/setup/install/providers/ecs) should mention that spinnaker can't leverage docker registries to drive ECS pipelines.

**Comment by dorbin** [comment]
@BrunoCarrier 
Is this a simple mention of what @colfredstan  says, or is there any more that needs to be said?

**Comment by BrunoCarrier** [comment]
That is correct @dorbin.  I think non ecr docker containers should be allowed without validation, and that the lack of validation should be underlined in the documentation, as well as what is needed for an ECS cluster instance to be able to use non ECR docker repositories.  What do you think?

**Comment by dorbin** [comment]
Yeah sounds good, Bruno. Can you add it?

**Comment by BrunoCarrier** [comment]
@dorbin @colfredstan here are 2 PRs that add support for non-ECR repositories:

https://github.com/spinnaker/clouddriver/pull/2616/files
https://github.com/spinnaker/orca/pull/2221

**Comment by dorbin** [comment]
Actually, I was inviting you to add the doc. You added support instead--even better! Thanks!
