### ISSUE TITLE
Authentication/SSL page has no instructions to verify SSH

### ISSUE THREAD

**Issue by designatevoid** [spinnaker/spinnaker.github.io#709]
Page: [/setup/security/authentication/ssl/](https://www.spinnaker.io/setup/security/authentication/ssl/)

Feedback:  Hello.  After going through the SSL instructions I realized that there is no way to debug/verify that everything is working correctly after running all of the specified commands.  In addition, even after running the commands running `hal config` produces:

"Problems in default.security:
- WARNING Your UI or API domain does not have override base URLs
  set even though your Spinnaker deployment is a Distributed deployment on a
  remote cloud provider. As a result, you will need to open SSH tunnels against
  that deployment to access Spinnaker."

A verification / troubleshooting section on this page would help immensely.

Thank you.

**Comment by dorbin** [comment]
@stewchen can you look into this and follow up with me, and I'll get the page updated?

**Comment by dorbin** [comment]
#721
