### ISSUE TITLE
Add ssh tunnel example

### ISSUE THREAD

**Issue by samuelson** [spinnaker/spinnaker.github.io#710]
Page: [/setup/install/deploy/](https://www.spinnaker.io/setup/install/deploy/)

Feedback:
The instructions say to connect to localhost:9000 which only works if you're running a web browser on the same machine where you've installed spinnaker.

How about adding an example of using SSH to tunnel:
ssh -L 9000:localhost:9000 -L 8084:localhost:8084 -L 8087:localhost:8087 spinnaker.example.com

**Comment by dorbin** [comment]
Josh, I'm going to close this issue in favor of #717, so we can make the whole process clear for all different use cases.
