### ISSUE TITLE
Remove mention of custom BOM for trying out canary

### ISSUE THREAD

**Issue by skim1420** [spinnaker/spinnaker.github.io#723]
Page: [/setup/canary/](https://www.spinnaker.io/setup/canary/)

Feedback:

Now that we've mainline released kayenta in 1.7.x, no need to direct users to custom BOM.

**Comment by dorbin** [comment]
Good catch.

@duftler , is it sufficient to remove this entirely, or do we want to specify a minimum version?

**Comment by duftler** [comment]
We should probably specify the minimum version of Spinnaker, just like we do for Halyard itself just above. Kayenta is available in v1.7.0 or higher.
