### ISSUE TITLE
Bitbucket Authorization header

### ISSUE THREAD

**Issue by thornpar** [spinnaker/spinnaker.github.io#725]
Page: [/setup/security/authentication/oauth/](https://www.spinnaker.io/setup/security/authentication/oauth/)

Feedback:

Regarding the userInfoUri on bitbucket its https://api.bitbucket.org/2.0/user
The problem is that it requires the access token to be sent in the Authorization header like this 

Authorization: Bearer {access_token}

Note the capital B in Bearer

When spinnaker sends the userInfo request it looks like this
Authorization: bearer {access_token}
And you will get a 403 or 401

I had to write a little proxyprogram that changes bearer to Bearer and set that proxy as my userInfoUri.

**Comment by dorbin** [comment]
@stewchen FYI

Hi, @thornpar , could you open this as an issue in [spinnaker/spinnaker](https://github.com/spinnaker/spinnaker/issues/)? 
Thanks!
