### ISSUE TITLE
How do I supply a jinja template to spinnaker?

### ISSUE THREAD

**Issue by briananderson1222** [spinnaker/spinnaker.github.io#746]
Page: [/guides/user/triggers/pubsub/](https://www.spinnaker.io/guides/user/triggers/pubsub/)

Feedback:

Towards the bottom of this page there is a sentence that reads:
> You would then need to supply a Jinja template to Spinnaker that translates this message payload to the Spinnaker artifact format:

and goes on to supply the template. This is probably a stupid question, but I was following the doc up to this point and don't understand where I can provide this. 

I'm trying to trigger from PubSub for GCR uploads where i'd love to be able to grab the commit sha (attached as the docker tag) as a variable that I can then provide to my expected artifact.

**Comment by ghost** [comment]
Are you using halyard?  For GCR subscriptions specifically you can use the `--message-format` flag when adding the subscription as follows:

```
hal config pubsub google subscription add --project my-project --json-path /path/to/service/account.key.json --subscription-name my-subscription --message-format GCR my-gcr-subscription
```

For messages that aren't from GCR you can go the route of manually specifying a jinja template using the `--template-path` flag.  Here's an example usage from the [GCS pubsub codelab](https://www.spinnaker.io/guides/tutorials/codelabs/pubsub-to-appengine/#configure-spinnaker-to-listen-to-the-google-cloud-pubsub-subscription):

```
hal config pubsub google subscription add --project my-project --json-path /path/to/service/account.key.json --subscription-name my-subscription --template-path /path/to/jinja/template my-gcs-subscription
```

After either of these you'll need to run `hal deploy apply` for the subscription to become available to stages.

**Comment by ghost** [comment]
(also, I completely agree that the docs fall down a bit here.  We explicitly describe the way to add templates in some docs but gloss over it in others)
