### ISSUE TITLE
Halyard install instructions missing user and permission information.

### ISSUE THREAD

**Issue by samuelson** [spinnaker/spinnaker.github.io#747]
Following these instructions:
https://github.com/spinnaker/spinnaker.github.io/blob/master/setup/install/halyard.md

I get a permission denied error on the third step. Does that mean I should use sudo? Or are there some permissions I'm supposed to grant my user. Am I supposed to create a "spinnaker" user like inside the docker container?

This is not something that people will just figure out it needs to actually be specified in the documentation.

**Comment by dorbin** [comment]
On the `docker run` command? 

Did you try sudo? (Just curious; I'm going to test this in some different scenarios)

**Comment by dorbin** [comment]
We've updated Halyard installation instructions to make Debian/Ubuntu/Mac OS the canonical hal install path, and updated the Docker install to indicate you might have to manuall change the permissions on mounted directories.
