### ISSUE TITLE
Announcement bar on landing page for Spinnaker Summit

### ISSUE THREAD

**Issue by skim1420** [spinnaker/spinnaker.github.io#749]
A static slim bar at top of spinnaker.io/ with link to spinnakersummit.com.

"Come join us at the second annual Spinnaker Summit, Oct 8-9 in Seattle, WA!"

**Comment by dorbin** [comment]
@skim1420 
Might be better with fewer words?

**Comment by skim1420** [comment]
Sgtm

**Comment by dorbin** [comment]
Turns out I kept the wording as you wrote it, @skim1420 . Looks better that way.
