### ISSUE TITLE
New distributed installation command is being missed by users

### ISSUE THREAD

**Issue by lwander** [spinnaker/spinnaker.github.io#797]
This seems to be coming up a lot now that we have a new doc structure: https://github.com/spinnaker/spinnaker/issues/2813

**Comment by dorbin** [comment]
@lwander can `hal config deploy edit --type distributed ...` be step one, before linking to configuring provider? If they're following those links to configure K8s, that might be why they're missing step 2.

**Comment by lwander** [comment]
The problem is they need to know the name of the account, which they might not have picked until configuring their provider... Maybe we can make that clear somehow?
