### ISSUE TITLE
Update docs to reflect if account permissions are required

### ISSUE THREAD

**Issue by lwander** [spinnaker/spinnaker.github.io#798]
See https://github.com/spinnaker/spinnaker/issues/2195 for context. @stewchen can you confirm?

**Comment by dorbin** [comment]
#813 (from Stew)

**Comment by dorbin** [comment]
@stewchen is this issue resolved, per your [spinnaker/halyard/pull/954](https://github.com/spinnaker/halyard/pull/954) and [spinnaker/spinnaker.github.io/pull/813](https://github.com/spinnaker/spinnaker.github.io/pull/813)?

**Comment by stewchen** [comment]
Docs pr is not merged yet, waiting on halyard release

**Comment by dorbin** [comment]
Yeah, I'm just wondering if that PR, when merged, is all we need?

**Comment by stewchen** [comment]
Yup! That's all
