### ISSUE TITLE
Document how to tweak/operationalize spinnaker

### ISSUE THREAD

**Issue by lwander** [spinnaker/spinnaker.github.io#810]
[Namely has given a great writeup](https://medium.com/namely-labs/sailing-with-spinnaker-deploying-a-better-cd-pipeline-to-dozens-of-engineers-and-services-b21dcfa0e1a1) of their Spinnaker journey. In it they cover a lot of configuration changes/tweaks that would be useful to know of without having to read Spinnaker's codebase. We should at the very least document these somewhere in a separate "setup" heading.

**Comment by lwander** [comment]
So I don't forget, it seems

```
redis:
  configuration:
    secure: true

```

Is important in some cases... need to dig into why

**Comment by dorbin** [comment]
Resolving this issue, per #811 

See [Productionize Spinnaker](https://www.spinnaker.io/setup/productionize/).
