### ISSUE TITLE
Missing Screenshot

### ISSUE THREAD

**Issue by zthroo** [spinnaker/spinnaker.github.io#843]
Page: [/guides/user/canary/judge/](https://www.spinnaker.io/guides/user/canary/judge/)

Feedback: In the section "Step 3: Metric comparison (classification)" a screenshot is referenced, but no screenshot is shown. "Each metric is classified as either “Pass”, “High”, or “Low” as shown in the screen shot below."

**Comment by avh121** [comment]
Resolved in #893
