### ISSUE TITLE
Move Ebook to far right of tabs, or remove

### ISSUE THREAD

**Issue by dorbin** [spinnaker/spinnaker.github.io#852]
It's probably sufficient to have the Read Our Ebook link on the homepage. We might not need an Ebook tab at the top of all pages. But if we do keep it there, it should probably be over next to Blog rather than in the middle of the documentation tabs. 

@tomaslin , WDYT? I can do it; I just want to check with you first.

**Comment by tomaslin** [comment]
how dare you!

yeah, this is fine
