### ISSUE TITLE
Headings in Pipeline Expressions guide are missing spaces

### ISSUE THREAD

**Issue by dorbin** [spinnaker/spinnaker.github.io#859]
There are some headings in the [Pipeline Expressions guide](https://www.spinnaker.io/guides/user/pipeline/expressions/) with no space between the # character(s) and the text, so [they're not rendering right on the page](https://www.spinnaker.io/guides/user/pipeline/expressions/#default-values).

**Comment by lwander** [comment]
Keep in mind, some of these need to be prefixed with `#` since this is how the functions are invoked: https://www.spinnaker.io/guides/user/pipeline/expressions/#alphanumerical-string-
