### ISSUE TITLE
Issue with connecting to Jenkins

### ISSUE THREAD

**Issue by prabhir2008** [spinnaker/spinnaker.github.io#867]
Page: [/guides/tutorials/codelabs/hello-deployment/](https://www.spinnaker.io/guides/tutorials/codelabs/hello-deployment/)

Feedback:
I have followed instructions in this lab on GCP instead of AWS.
While configuring I have observed below. 
1. I could not find file named spinnaker-local.yml instead I am seeing file spinnaker.yml
2. Considering this I have added below in that file for jenkins
 jenkins:
    enabled: true
    name: jenkins # The display name for this server
    baseUrl: http://35.196.147.78:8080
    username: user
    password: pass

Also Igor is also enabled.

I am able to ping the jenkins host from spinnaker. After restart of spinnaker service I a still unable to see the jenkins master and jobs for it.

Could you please tell how to proceed in this? spinnnaker installation is done using preexisting image VM from GCP(test/quick install).

Thanks and Regards,
prabhir

**Comment by avh121** [comment]
@lwander do you have a sense of why the jenkins master might not be showing up?

**Comment by lwander** [comment]
Best guess is that Spinnaker needs to be restarted. 

In any case, this might best be answered in our [Spinnaker Slack](https://spinnakerteam.slack.com). If you're not already a member, you can join using [this link](http://join.spinnaker.io).
