### ISSUE TITLE
Can't deep-link to content inside zippies

### ISSUE THREAD

**Issue by ghost** [spinnaker/spinnaker.github.io#875]
One unfortunate side-effect of putting a section of content into a closed zippy is that pasting a link  to that section in the URL bar wont jump you to that spot on the page.  Here's an example link:

https://www.spinnaker.io/setup/install/environment/#required-halyard-invocations-1

Clicking this should ideally open up the "Local Git" zippy and scroll the page such that the "Required Halyard Invocations" section is on-screen.

**Comment by lwander** [comment]
Good catch, I thought I ran into this but figured I was doing something wrong
