### ISSUE TITLE
Ambiguos doc page

### ISSUE THREAD

**Issue by infestonn** [spinnaker/spinnaker.github.io#889]
Page: [/setup/security/authorization/ldap/](https://www.spinnaker.io/setup/security/authorization/ldap/)

Feedback:
Would be nice to mention how to enable fiat on LDAP page.
`hal config security authz enable`
If i don't use git groups or gsuit groups and navigate to LDAP authorization page i can't figure out why fiat does not even deploy by hal

**Comment by dorbin** [comment]
@stewchen 
We have doc for `hal config security authn ldap`. I don't see anything for `hal config security authz ldap`. 
Does such a thing exist? If so, would it fix this problem? If not, what is missing here?

Thanks!

**Comment by stewchen** [comment]
Halyard support for Fiat ldap has not been implemented yet - definitely will be on the roadmap soon to fix this issue. For now, we should add the commands for deploying fiat via halyard, in conjunction with the `fiat-local` config override:
```
hal config security authz edit --type ldap
hal config security authz enable
```

**Comment by dorbin** [comment]
#892
