### ISSUE TITLE
Deploy Spinnaker locally using Minikube (Kubernetes)

### ISSUE THREAD

**Issue by costimuraru** [spinnaker/spinnaker.github.io#890]
Recently I tried to lookup a guide to deploy Spinnaker locally, on Minikube (Kubernetes). 

The closest thing I cam across was this tutorial on how to install Spinnaker on Google Kubernetes Engine:
https://www.spinnaker.io/setup/quickstart/halyard-gke/

However, some steps were missing (eg. how to setup the docker-registry that's not in GKE).

I did manage to make it work, after getting help from Slack.

As a result I put some notes here:
https://costimuraru.wordpress.com/2018/07/06/deploying-spinnaker-on-minikube-kubernetes-using-hal/

Do you think it would be worth it to create a similar page on spinnaker.io with the steps to install Spinnaker in Minikube (eg. on https://www.spinnaker.io/setup/quickstart/halyard-minikube/)?

**Comment by dorbin** [comment]
@costimuraru 
The main setup flow, specifically [here](https://www.spinnaker.io/setup/install/environment/), and the linked [page](https://www.spinnaker.io/setup/install/providers/kubernetes/) for configuring the K8s provider, should work the same for Minikube as for (legacy) K8s. And it includes the requirement for having a Docker Registry, and links to the page for setting that up.

Please re-open this if you find this insufficient :)
