### ISSUE TITLE
Bakery instructions seem unrelated

### ISSUE THREAD

**Issue by ttomsu** [spinnaker/spinnaker.github.io#931]
Page: [/setup/bakery/google/](https://www.spinnaker.io/setup/bakery/google/)

Feedback:
The page includes the lines:

> For example, to set the default zone:

then provides a command for editing a network:

> hal config provider google bakery edit --network $YOUR_NETWORK

that appears on the surface to have nothing to do with a zone. @duftler, is this intentional?

**Comment by dorbin** [comment]
`hal config provider google bakery edit --zone [us-wherever]`, right @duftler ?

**Comment by duftler** [comment]
Yup, that's right. It supports setting both the default zone and the default network, but that wording and the actual example don't match.

**Comment by dorbin** [comment]
#994
