### ISSUE TITLE
`deck-start.sh` script needs netcat

### ISSUE THREAD

**Issue by ttomsu** [spinnaker/spinnaker.github.io#946]
Page: [/setup/install/environment/](https://www.spinnaker.io/setup/install/environment/)

Feedback:

The local git based installation threw a bunch of these at me during startup:

```
/home/ttomsu/dev/spinnaker/scripts/deck-start.sh: line 26: nc: command not found
```

Needed to `sudo apt-get install netcat` to make them go away - this should probably be added to the docs and/or corrected in the `desk-start.sh` script. (cc @lwander )

**Comment by lwander** [comment]
Hey @brandonnelson3 I assigned you since you've implemented the local git installation

**Comment by brandonnelson3** [comment]
deck-start.sh uses netcat as a sort of health check looking to block until the yarn server is up in LocalGit mode. We could, install netcat if its missing, or alternatively use curl if available, or just document netcat as a prereq.

This occurs on the GCP Drawfork debian base image, but does not manifest on any of the Ubuntu flavors. 

Thoughts?

**Comment by lwander** [comment]
I would just document that it's needed in the installation instructions for this particular install path. I wouldn't try to install it since this could be running on a number of different systems, and we'll just be creating a headache for ourselves

**Comment by ttomsu** [comment]
Given that the instructions on that page already have you install `curl`  if it isn't already available, I'd vote for just using `curl`.

**Comment by dorbin** [comment]
For now, just adding the instruction to install netcat
