### ISSUE TITLE
Spinnaker Versions

### ISSUE THREAD

**Issue by raykoch** [spinnaker/spinnaker.github.io#989]
Page: [/community/releases/versions/](https://www.spinnaker.io/community/releases/versions/)

Feedback:

So, can anyone tell me why the Spinnaker site says these version numbers https://www.spinnaker.io/community/releases/versions/
but on GitHub Repo it is totally different?

**Comment by duftler** [comment]
The versions listed on the site are the top-level versions, and the approach is explained at the top of that same page.

The github repo's for each service (and for spinnaker/spinnaker) show the versions/tags that are applied as part of that top-level build process, but they also include an independent version namespace for folks who are not running the top-level, umbrella version.

**Comment by lwander** [comment]
https://www.spinnaker.io/community/faqs/#why-dont-the-versions-used-in-each-subcomponent-in-the-new-top-level-versioned-spinnaker-match-those-in-the-github-releases
